CREATE TABLE numgeo (
	OPERADOR TINYTEXT NULL,
	SERVICIO TINYTEXT NULL,
	MODALIDAD TINYTEXT NULL,
	LOCALIDAD TINYTEXT NULL,
	INDICATIVO TINYTEXT NULL,
	BLOQUE TINYTEXT NULL,
	RESOLUCION TINYTEXT NULL,
	FECHA DATE NULL
)
ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_swedish_ci;
